# Generated by Django 2.2.7 on 2019-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=20, verbose_name='Localidad')),
                ('proyecto', models.CharField(max_length=70, verbose_name='Nombre del proyecto')),
                ('tipo_proyecto', models.CharField(max_length=30, verbose_name='Nombre del proyecto')),
                ('perfil_1', models.IntegerField(default=0, verbose_name='Perfil 1')),
                ('perfil_2', models.IntegerField(default=0, verbose_name='Perfil 2')),
                ('perfil_3', models.IntegerField(default=0, verbose_name='Perfil 3')),
                ('perfil_4', models.IntegerField(default=0, verbose_name='Perfil 4')),
                ('perfil_5', models.IntegerField(default=0, verbose_name='Perfil 5')),
            ],
        ),
    ]
