# Generated by Django 2.2.7 on 2019-12-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191127_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto',
            field=models.CharField(max_length=70, unique=True, verbose_name='Nombre del proyecto'),
        ),
    ]
