# Generated by Django 2.2.7 on 2019-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191201_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='slug_localidad',
            field=models.SlugField(null=True, verbose_name='Slug Localidad'),
        ),
    ]
